
* Vorlesungsmitschriften von Studenten der Friedrich-Schiller-Universität Jena
Das Repository ist/war ein Projekt von Studenten der [[http://www.fmi.uni-jena.de/][Fakultät für
Mathematik und Informatik]] der [[http://www.uni-jena.de/][Friedrich-Schiller-Universität
Jena]]. Darin enthalten sind zum Großteil Mitschriften von
Vorlesungen. Weiterhin liegen hier Hooks für Subversion, die den
eingecheckten Quellcode prüfen und automatisch in PostScript und PDF
übersetzen. Ein kleinerer Teil ist für die Aktualisierung der [[http://uni-skripte.lug-jena.de/][Webseite]]
zuständig.

** Vorlage für neue Skripte
   Das Verzeichnis [[https://github.com/qbi/uni-skripte/vorlage][vorlage]] enthält ein Template für neue
   Vorlesungen. Für ein neues Skript wird üblicherweise ein
   Verzeichnis mit dem Muster ~familienname-vorlesungsname~ angelegt
   und die [[https://github.com/qbi/uni-skripte/vorlage/skript.ltx][Skript-Vorlage]] hineinkopiert. In der Vorlage sind alle
   wichtigen Pakete für LaTeX enthalten.
** Webseiten
   Das Verzeichnis [[https://github.com/qbi/uni-skripte/web][web]] enthält die Dateien für die Webseite. Die
   Seiten basieren auf Ophelia und haben ein wenig Automatisierung
   drin.
** Werkzeuge
   Das Verzeichnis [[https://github.com/qbi/uni-skripte/werkzeuge][werkzeuge]] enthält diverse Hilfprogramme zur
   Verwaltung der Skripte. Früher wurden die Dateien mit Subversion
   verwaltet. Die Software bietet u.a. pre- und post-commit-Hooks an,
   d.h. Programme, die vor oder nach jedem Commit ausgeführt werden.
   - [[https://github.com/qbi/uni-skripte/werkzeuge/erzeuge-alle.sh][erzeuge-alle.sh]] ist ein Shellskript, welches versucht, alle
     Skripte neu zu bauen.
   - [[https://github.com/qbi/uni-skripte/werkzeuge/erzeuge-ausgabe.sh][erzeuge-ausgabe.sh]] ist ein Shellskript, welches einige
     Informationen (Fehler, Warnungen etc.) zum Build zusammenstellt.
   - give\_away.c
     Mit diesem Programm lässt sich der Eigentümer einer
     Datei ändern. Wenn für das Programm das suid-Bit gesetzt ist,
     wird eine Kopie der Datei erstellt, welche dem Eigentümer des
     Programms gehört. Diese ersetzt dann die alte Datei.
   - [[https://github.com/qbi/uni-skripte/werkzeuge/skript-check][skript-check]] ist ein Perl-Skript. Das prüft den Quellcode auf
     typische LaTeX-Fehler und druckt Warnungen aus.
   - [[https://github.com/qbi/uni-skripte/werkzeuge/statistik][statistik]] ist ein Perl-Skript. Das erstellt eine Übersicht, wie
     oft die Skripte abgerufen wurden.

** Mitschriften
   Momentan gibt es die folgenden Skripte:

   - [[https://github.com/qbi/uni-skripte/alt-linopt][alt-linopt]]
     Lineare Optimierung bei Prof. Walter Alt
   - [[https://github.com/qbi/uni-skripte/alt-nichtlinopt][alt-nichtlinopt]]
     Einführung in die nichtlineare Optimierung bei Prof. Walter Alt
   - [[https://github.com/qbi/uni-skripte/carl-ana1][carl-ana1]]
     Analysis 1 bei Prof. Bernd Carl
   - [[https://github.com/qbi/uni-skripte/carl-ana2][carl-ana2]]
     Analysis 2 bei Prof. Bernd Carl
   - [[https://github.com/qbi/uni-skripte/carl-hoehereana][carl-hoehereana]]
     Höhere Analysis bei Prof. Bernd Carl
   - [[https://github.com/qbi/uni-skripte/engelbert-mass-integral][engelbert-mass-integral]]
     Maß und Integral bei Prof. Engelbert
   - [[https://github.com/qbi/uni-skripte/erhard-komm-sys][erhard-komm-sys]]
     Kommunikationstechnik bei Prof. Werner Erhard
   - [[https://github.com/qbi/uni-skripte/fey-recharch][fey-recharch]]
     Rechnerarchitektur 1 und 2 bei Prof. Fey
   - [[https://github.com/qbi/uni-skripte/fichtner-ewms][fichtner-ewms]]
     Elementare Wahrscheinlichkeitstheorie und Mathematische Statistik
     bei Prof. Karl-Heinz Fichtner
   - [[https://github.com/qbi/uni-skripte/giesen-algogeo][giesen-algogeo]]
     Algorithmische Geometrie bei Prof. Joachim Giesen
   - [[https://github.com/qbi/uni-skripte/haberland-algebra][haberland-algebra]]
     Algebra 1 bei PD Dr. Klaus Haberland
   - [[https://github.com/qbi/uni-skripte/haberland-zahlen][haberland-zahlen]]
     Zahlentheorie PD Dr. Klaus Haberland
   - [[https://github.com/qbi/uni-skripte/hecker-info3][hecker-info3]]
     Informatik 3 bei  Prof. Hans-Dietrich Hecker
   - [[https://github.com/qbi/uni-skripte/hecker-parallel][hecker-parallel]]
     Parallele Algorithmen bei Prof. Hans-Dietrich Hecker
   - [[https://github.com/qbi/uni-skripte/hempel-info4][hempel-info4]]
     Informatik 4 bei Prof. Harald Hempel
   - [[https://github.com/qbi/uni-skripte/hinrichs-fourierana][hinrichs-fourierana]]
     Fourieranalysis bei PD Dr. Aicke Hinrichs
   - [[https://github.com/qbi/uni-skripte/kubieziel-itsich][kubieziel-itsich]]
     IT-Sicherheit bei Jens Kubieziel
   - [[https://github.com/qbi/uni-skripte/kuelshammer-algebra1][kuelshammer-algebra1]]
     Algebra 1 bei Prof. Burkhard Külshammer
   - [[https://github.com/qbi/uni-skripte/kuelshammer-gruppentheorie][kuelshammer-gruppentheorie]]
     Gruppentheorie  bei Prof. Burkhard Külshammer
   - [[https://github.com/qbi/uni-skripte/kuelshammer-lie][kuelshammer-lie]]
     Lie-Algebren bei Prof. Burkhard Külshammer
   - [[https://github.com/qbi/uni-skripte/kuelshammer-ringtheorie][kuelshammer-ringtheorie]]
     Ringtheorie  bei Prof. Burkhard Külshammer
   - [[https://github.com/qbi/uni-skripte/kuespert-dbs1][kuespert-dbs1]]
     Datenbanksysteme 1 bei Prof. Klaus Küspert
   - [[https://github.com/qbi/uni-skripte/kuespert-verteilte-dbs][kuespert-verteilte-dbs]]
     Verteilte Datenbanksystemen und Client-Server-Systeme bei
     Prof. Klaus Küspert
   - [[https://github.com/qbi/uni-skripte/leopold-hoehere-ana][leopold-hoehere-ana]]
     Höhere Analysis 1 bei Prof. Hans-Gerd Leopold
   - [[https://github.com/qbi/uni-skripte/linde-stochastik][linde-stochastik]]
     Mathematik für Informatiker 3 bei Prof. Linde
   - [[https://github.com/qbi/uni-skripte/linde-stochastik-zusfa][linde-stochastik-zusfa]]
     Stochastik für Informatiker und Regelschullehrer bei Prof. Werner
     Linde
     Eine Auswahl wichtiger Definitionen und Aussagen
   - [[https://github.com/qbi/uni-skripte/linde-wtheorie][linde-wtheorie]]
     Wahrscheinlichkeitstheorie bei Prof. Werner Linde
   - [[https://github.com/qbi/uni-skripte/lischke-mengenlehre][lischke-mengenlehre]]
     Mengenlehre als Fundament für Mathematik und Informatik bei
     Dr. Gerhard Lischke
   - [[https://github.com/qbi/uni-skripte/matveev-laag][matveev-laag]]
     Lineare Algebra und analystische Geometrie bei Prof. Matveev
     Dies sind nur Zusammenfassungen von Aussagen in der Vorlesung,
     keine vollständige Mitschrift.
   - [[https://github.com/qbi/uni-skripte/mundhenk-logik][mundhenk-logik]]
     Logik bei Prof. Martin Mundhenk
   - [[https://github.com/qbi/uni-skripte/niedermeier-komplexitaet][niedermeier-komplexitaet]]
     Komplexitätstheorie bei Prof. Rolf Niedermeier
   - [[https://github.com/qbi/uni-skripte/richter-geozerl][richter-geozerl]]
     Geometrische Zerlegungen bei PD Dr. Christian Richter
   - [[https://github.com/qbi/uni-skripte/schmeisser-ana3][schmeisser-ana3]]
     Analysis 3 bei Prof. Hans-Jürgen Schmeißer
   - [[https://github.com/qbi/uni-skripte/schmeisser-hoehere-ana][schmeisser-hoehere-ana]]
     Höhere Analysis bei Prof. Hans-Jürgen Schmeißer
   - [[https://github.com/qbi/uni-skripte/vogel-dml2][vogel-dml2]]
     Diskrete Mathematik und Logik bei Dr. Jörg Vogel
   - [[https://github.com/qbi/uni-skripte/vogel-info4][vogel-info4]]
     Grundlagen der theoretischen Informatik bei Dr. Jörg Vogel
   - [[https://github.com/qbi/uni-skripte/vogel-krypt][vogel-krypt]]
     Kryptologie bei Dr. Jörg Vogel
   - [[https://github.com/qbi/uni-skripte/weber-funktionentheorie][weber-funktionentheorie]]
     Funktionentheorie bei Prof. Albin Weber
